### ISSUE TITLE
reinterpret_cast<unsigned_t> or reinterpret_cast<std::uintptr_t> in logger.cpp

### ISSUE THREAD

**Issue by myupctoys** [kmilo17pet/QuarkTS-cpp#9]
BTW no criticism with your code, loving qlibs and QuarkTS

Compiling on GCC 5.10 on a W10 PC to setup some unit tests and ran into an issue with logger.cpp

Line 203 Example in logger.cpp
`(void)util::unsignedToString( reinterpret_cast<unsigned_t>( p ), buffer, 16U ); // skipcq: CXX-C1000`

Compiled with an error for 5 lines all related reinterpret_cast<unsigned_t>

> _E:\CSandbox\QuarkTS-cpp\src\logger.cpp|121|error: cast from 'const void*' to 'qOS::unsigned_t' {aka 'long unsigned int'} loses precision [-fpermissive]|_

Tried different CPP standards just in case, but no solution.

Changing `reinterpret_cast<unsigned_t>` to `reinterpret_cast<std::uintptr_t>` fixes the compiler issue but wondering if this is a valid solution or a more project centric solution might be better.

_(void)util::unsignedToString( reinterpret_cast<std::uintptr_t>( &sm.getTop() ), buffer, 16 ); // skipcq: CXX-C1000_

Everything else compiles fine.

**Comment by myupctoys** [comment]
Sorry, so you can compare apples with apples. Cutting and pasting and I stuffed it. Now the correct lines. Both refer to the same issue anyway.

Line 203 Example in logger.cpp
`(void)util::unsignedToString( reinterpret_cast<unsigned_t>( &sm.getTop() ), buffer, 16 ); // skipcq: CXX-C1000`

Compiled with an error for 5 lines all related reinterpret_cast<unsigned_t>

> E:\CSandbox\QuarkTS-cpp\src\logger.cpp|121|error: cast from 'const void*' to 'qOS::unsigned_t' {aka 'long unsigned int'} loses precision [-fpermissive]|

Tried different CPP standards just in case, but no solution.

Changing reinterpret_cast<unsigned_t> to reinterpret_cast<std::uintptr_t> fixes the compiler issue but wondering if this is a valid solution or a more project centric solution might be better.

`(void)util::unsignedToString( reinterpret_cast<std::uintptr_t>( &sm.getTop() ), buffer, 16 ); // skipcq: CXX-C1000`

Everything else compiles fine.

**Comment by kmilo17pet** [comment]
hi @myupctoys , thank you for your issue report. I already fixed this in the last commit by using uintptr_t as you suggested. (or release 1.5.9). My initial concern with using uintptr_t was related to portability, some old compilers did not define this datatype. One way or another, I am only taking into account the standard from c++11 and uintptr_t should be there
